### ISSUE TITLE
Unable to use PhoneNumber detector feature in WebView

### ISSUE THREAD

**Issue by kkadapa** [atomic14/react-native-web-view#8]
I followed your youtube video https://www.youtube.com/watch?v=1KztsEdrhr8&ab_channel=atomic14 I am trying to enable the PhoneNumber data detector in WKWebView on the Swift side inside the `WebView.Swift` file. However, I receive a blank screen when I run the below directly on my phone using Xcode. Here is my sample document with Phone Numbers https://kkadapa.github.io/file-sample_100kB.doc This gist consists of working Native Swift code https://gist.github.com/kkadapa/fa09807e2e27af75adcbe4f481931ad3 Could you kindly help?

```
init() {
    super.init(frame: CGRect.zero)
    webView.translatesAutoresizingMaskIntoConstraints = false;
    let webConfiguration = WKWebViewConfiguration()
    webConfiguration.dataDetectorTypes = [.all]
    webConfiguration.dataDetectorTypes = .phoneNumber
    webView = WKWebView(frame: .zero, configuration: webConfiguration)   
    addSubview(webView)
    addConstraint(NSLayoutConstraint(item: webView, attribute: .left, relatedBy: .equal, toItem: self, attribute: .left, multiplier: 1.0, constant: 0.0))
    addConstraint(NSLayoutConstraint(item: webView, attribute: .right, relatedBy: .equal, toItem: self, attribute: .right, multiplier: 1.0, constant: 0.0))
    addConstraint(NSLayoutConstraint(item: webView, attribute: .top, relatedBy: .equal, toItem: self, attribute: .top, multiplier: 1.0, constant: 0.0))
    addConstraint(NSLayoutConstraint(item: webView, attribute: .bottom, relatedBy: .equal, toItem: self, attribute: .bottom, multiplier: 1.0, constant: 0.0))
    webView.navigationDelegate = self;
  }
```

**Comment by cgreening** [comment]
The WebView is designed to view HTML files - I'm not sure your doc file will work.

**Comment by kkadapa** [comment]
The idea is if an HTML page has to click to call phone numbers you can call using iPhone https://developer.apple.com/documentation/webkit/wkdatadetectortypes 

In Swift using WkWebView, you can manually set this configuration like below and it automatically detects phone numbers for click to call...

let webConfiguration = WKWebViewConfiguration()
         webConfiguration.dataDetectorTypes = [.all]
         webConfiguration.dataDetectorTypes = .phoneNumber

**Comment by cgreening** [comment]
Not sure what problem you are having, but it seems to work fine for me. I've pushed up version that works for me.

![Simulator Screen Shot - iPod touch (7th generation) - 2021-06-14 at 11 37 23](https://user-images.githubusercontent.com/706944/121879702-0ce81900-cd05-11eb-931c-2031dee24786.png)
